INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.3:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:14:05] "GET / HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:14:06] "GET /static/images/search.png HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:14:06] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:14:06] "GET /static/images/bg.jpg HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:14:07] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:14:35] "POST /search HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:14:35] "GET /static/css/results.css HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.3:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:26:43] "GET / HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:26:43] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:26:43] "GET /static/images/search.png HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:26:44] "GET /static/images/bg.jpg HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:27:01] "POST /search HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [17/Mar/2023 03:27:02] "GET /static/css/results.css HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.94:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:15:05] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:15:05] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:15:06] "GET /static/images/search.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:15:06] "GET /static/images/bg.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:15:06] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR:views:Exception on /search [POST]
Traceback (most recent call last):
  File "c:\Users\ramam\Desktop\FWP\views.py", line 31, in get_content
    csv_file = asyncio.run(fetch_channel_data(channel_url))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "c:\Users\ramam\Desktop\FWP\views.py", line 157, in fetch_channel_data
    dict_writer.writerow(row_dict)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 93: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ramam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ramam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ramam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ramam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\ramam\Desktop\FWP\views.py", line 44, in get_content
    logging.INFO(e)
TypeError: 'int' object is not callable
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:15:32] "[35m[1mPOST /search HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.94:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:18:52] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:18:52] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:18:52] "[36mGET /static/images/search.png HTTP/1.1[0m" 304 -
ERROR:views:Exception on /search [POST]
Traceback (most recent call last):
  File "c:\Users\ramam\Desktop\FWP\views.py", line 39, in get_content
    os.remove(csv_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\ramam\\Desktop\\FWP/@PatrickAlphaC.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ramam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ramam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ramam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ramam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\ramam\Desktop\FWP\views.py", line 44, in get_content
    logging.INFO(e)
TypeError: 'int' object is not callable
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:18:59] "[35m[1mPOST /search HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.94:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:26:42] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:26:43] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:26:43] "[36mGET /static/images/bg.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:26:43] "[36mGET /static/images/search.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:26:57] "POST /search HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 23:26:57] "GET /static/css/results.css HTTP/1.1" 200 -
